import type { ApiError } from "@/lib/api/types";
import { getSimulation } from "@/mocks/store";

export const dynamic = "force-dynamic";

/**
 * GET /api/documents/{id} — one document, for the review screen.
 *
 * `RouteContext` is generated by `next dev` / `next build` and is globally
 * available; `params` is a Promise in this version of Next and must be awaited.
 */
export async function GET(
  _request: Request,
  context: RouteContext<"/api/documents/[id]">,
): Promise<Response> {
  const { id } = await context.params;
  const documento = getSimulation().get(id);

  if (!documento) {
    return Response.json(
      {
        codigo: "documento_nao_encontrado",
        mensagem: `Documento ${id} não existe.`,
      } satisfies ApiError,
      { status: 404 },
    );
  }

  return Response.json(documento);
}
